name: Deploy

on: 
  workflow_dispatch

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:

    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-0
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install binaries
      run: yarn install

    - name: Build
      run: ./scripts/deploy_demo.sh
